### ISSUE TITLE
Capture last Scroll Position

### ISSUE THREAD

**Issue by jhowLC** [WashingtonGuedes/jquery-do-scroll#4]
Hello, Your plugin is amazing, but may be better if you add a function to save the last position Scroll.
Every time that the user leave the page, the plugin save the last position and when the user came back, the last position is set.
This can be controlled by a variable in the properties.
It's necessary to save the element too, because if I had 2 scrolls in the same page, both need's to cameback to last position.

**Comment by washington-guedes** [comment]
It is now a standard behaviour for wrappers that have an **`id`**. (The example was updated to address that)
You can turn it off with the `initialSpace` property (because it has priority over storage), or you can manually clear the key from `localStorage`.

Thanks for the proposal :) That was a really nice upgrade!!
